# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6994e6af7e6c66416d3008741bcb94a421501436feea3134224710b2984c22f6aa6087e8c136e78b7208ac849ca9bcd075daa6e39e7cd18c74fcfd89f45e101

test:
  secret_key_base: 612b4092d750fe1e165f98f81e9d88d1560fdd3c1a4258cd230f236de637d3cbc200040b0b3bd7cfc52421a10cf3ba7835257b9edc168b5a8734e2466404b1bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
